version: "4.0"
services:
  jeager-service:
    image: jaegertracing/all-in-one:latest
    environment:
#      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - "16686:16686"
      - "16687:16687"
#      - "9411:9411"
      - "4318:4318"
      - "4317:4317"
    volumes:
      - ./data/badger:/badger

