version: "4.0"
services:
  jeager-service:
    image: jaegertracing/all-in-one:latest
    environment:
#      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_HOST_PORT=4317
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
#      - "9411:9411"
      - "4318:4318"
      - "4317:4317"
