server:
  port: 8084
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - bg-field1
        - bg-field2
        - bg-field3
        - bg-field4
      correlation-enabled: true
      correlation-fields:
        - col-field
    propagation:
      type: W3C
spring:
  application:
    name: Service-D